### ISSUE TITLE
Scope and relationship to other packages

### ISSUE THREAD

**Issue by sethaxen** [chrisbrahms/Hankel.jl#1]
Nice package!

I'm planning to implement a discrete spherical Hankel transform, also following the pattern of AbstractFFTs. Since you have the Hankel package name in the registry, would your package be a good place to contribute this (else I would create a SphericalHankel.jl)? It would be nice if the interfaces were similar.

I noticed you currently implement only the zero-order DHT. There's also @jagot's package https://github.com/jagot/Hankel.jl, which is stale but implements additional orders, seemingly following the same papers.

**Comment by chrisbrahms** [comment]
Thanks!

I've just spun this package out of a bigger project I'm working on, which only uses the 0th-order transform, hence the limited scope so far. Non-0 orders are mostly a matter of adding appropriate test cases, the algorithm is identical. I'd be very happy to make this a more general package implementing other approaches as well. Does the spherical DHT follow the same pattern as the QDHT of picking sampling points at zeros of the basis functions, etc?

**Comment by sethaxen** [comment]
> Non-0 orders are mostly a matter of adding appropriate test cases, the algorithm is identical.

Yeah, I noticed that as well. I only myself need the 1/2-order transform for my project, but it's nice to generalize.

> I'd be very happy to make this a more general package implementing other approaches as well. 

Great! I'm not thinking of adding additional approaches (at least not yet). I'm more thinking of extending the approach you've implemented so it works for non-0 orders with convenient functions for the SHT.

> Does the spherical DHT follow the same pattern as the QDHT of picking sampling points at zeros of the basis functions, etc?

The spherical DHT (DSHT) I'm thinking of is just a reparameterization of the usual DHT.
e.g. the usual HT is
`$\tilde{f}_\nu(k) = \sqrt{\frac{2}{\pi}} \int_0^\infty f(r) J_\nu(r k) r dr$`
The SHT as I define it is (there are different conventions; this one is chosen because forward and reverse are the same):
`$\hat{g}_\nu(k) = \sqrt{\frac{2}{\pi}} \int_0^\infty g(r) j_\nu(r k) r^2 dr = \int_0^\infty g(r) \sqrt{\frac{r}{k}} J_{\nu + 1/2}(r k) r dr = \frac{1}{\sqrt{k}} \tilde{h}_{\nu+1/2}(k)$`
where `$h(r) = g(r) \sqrt{r}$`
While the user can get the DSHT by pre- and post-multiplying the necessary factors, a DSHT implementation would simply modify `T` and the constants in `mul!` and `ldiv!` so that this isn't necessary.

I don't understand how `integrateR` and `integrateK` are derived, so I'm not certain if/how they need to be modified for non-0 orders or the DSHT.

It would probably also be good to release the `Float64` type constraints, allowing a generic `Real`.

If this sounds good to you, I'll open a PR.

**Comment by chrisbrahms** [comment]
> The spherical DHT (DSHT) I'm thinking of is just a reparameterization of the usual DHT.

Yes, I see now. That should be quite straightfoward then! The non-0 orders are nearly there already, I will just need to implement the test cases from the Guizar-Sicairos paper to make sure it works.

> I don't understand how `integrateR` and `integrateK` are derived, so I'm not certain if/how they need to be modified for non-0 orders or the DSHT.

I have this written up somewhere, I will add it to the docs. 

> It would probably also be good to release the `Float64` type constraints, allowing a generic `Real`.

Good point--turned out to be quite quick to do anyway.

> If this sounds good to you, I'll open a PR.

Yes, sounds excellent. I should find some time later today to finish the non-0 order transform, but everything after that I will put into PRs as well so you're not trying to hit a moving target.

**Comment by sethaxen** [comment]
> I have this written up somewhere, I will add it to the docs.

Thanks!

> Yes, I see now. That should be quite straightfoward then! The non-0 orders are nearly there already, I will just need to implement the test cases from the Guizar-Sicairos paper to make sure it works.

> Yes, sounds excellent. I should find some time later today to finish the non-0 order transform, but everything after that I will put into PRs as well so you're not trying to hit a moving target.

Great! Should have some time to to put it together near the end of the week.

**Comment by chrisbrahms** [comment]
Derivation for the integrals can now be found at https://chrisbrahms.github.io/Hankel.jl/dev/derivations/

Non-zero orders are now implemented and somewhat tested, though I'd suggest you add some test cases specifically for the 1/2-order transform just to make sure.

**Comment by chrisbrahms** [comment]
Closed by #6
