### ISSUE TITLE
incorrect nodes at high orders due to incorrect zeros

### ISSUE THREAD

**Issue by xzackli** [chrisbrahms/Hankel.jl#14]
Thanks for a great package!

Since this package depends on FunctionZeros, it suffers from https://github.com/jlapeyre/FunctionZeros.jl/issues/10 (that package doesn't work for orders larger than a few) and thus Hankel.jl cannot set up a plan for those orders. For example, here's a quick selection of nodes,

```julia
using Hankel
R = 1.0
N = 32
q = QDHT(10, R, N)
print(q.r[4:7])
```
```
[0.21586560553503556, 0.3827577984254705, 3.847210992460738, 0.24445021648591286]
```
These nodes aren't monotonically increasing!

I imagine this can be fixed by using a more reliable source of zeros, perhaps GSL? FunctionZeros is a very tiny package, so maybe a pure Julia replacement using more robust methods might be helpful.

**Comment by xzackli** [comment]
For example, if you're willing to include a GSL.jl dependency, `sf_bessel_zero_Jnu_e` is a drop-in replacement for the FunctionZeros call.

**Comment by sethaxen** [comment]
Thanks for the issue. We do need a more reliable solution for high orders. And a great deal is known about computation of the zeros of bessel functions. e.g. http://dlmf.nist.gov/10.21.vi.

> For example, if you're willing to include a GSL.jl dependency, `sf_bessel_zero_Jnu_e` is a drop-in replacement for the FunctionZeros call.

I do think we should drop FunctionZeros as a dependency. It is basically just a wrapper for Roots, which is actively maintained, unlike FunctionZeros whose recent maintenance I have initiated to fix issues we have faced here. But as @xzackli brings up, even this use of Roots breaks down for us. Using GSL would definitely be the fastest way to resolve this issue. It also would not take long to implement a pure Julia solution. I'd like to look into this. @chrisbrahms does this sound fine?

**Comment by sethaxen** [comment]
As noted in https://github.com/chrisbrahms/Hankel.jl/pull/15#issuecomment-766308905, recent releases of FunctionZeros have also not been registered.

**Comment by chrisbrahms** [comment]
Yes, this clearly needs fixing. Originally I avoided it as a heavy dependency, but using GSL seems like the best option. However if I understand [this](https://github.com/JuliaMath/GSL.jl/blob/master/Project.toml) correctly it will then restrict SpecialFunctions back to v0.10?

**Comment by sethaxen** [comment]
> However if I understand [this](https://github.com/JuliaMath/GSL.jl/blob/master/Project.toml) correctly it will then restrict SpecialFunctions back to v0.10?

Yeah that's right. And bound Julia to >= v1.3. I'm locally testing using GSL, and the tests pass with GSL v0.6 which didn't have the Julia version bound, so that's not an issue. I'll open a PR there to bump its SpecialFunctions bound.

**Comment by sethaxen** [comment]
GSL is now compatible with SpecialFunctions v1 https://github.com/JuliaRegistries/General/pull/28540

**Comment by jlapeyre** [comment]
> And a great deal is known about computation of the zeros of bessel functions

I wanted to avoid using these higher order approximations for performance reasons. Of course the low order approximation fails for higher nu. I originally wrote the package for only the orders I needed at the time... Maybe the GSL function zeros were not available at the time. I'll try to find some time to investigate when and how to use the higher order approximations, eg conditionally, or for all orders, etc.

I also forgot how to bump a version number(!) That's next on my list. Anyway, I think it's a good solution to depend on GSL, as it is better maintained.
