### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by sethaxen** [chrisbrahms/Hankel.jl#23]
@chrisbrahms when tagging a new release (https://github.com/JuliaRegistries/General/pull/38708#issuecomment-859974982) it came to light that this package doesn't have a license. Any issues with me adding an MIT license here, which is highly permissive and also standard for Julia packages?

**Comment by sethaxen** [comment]
@chrisbrahms does this sound fine?

**Comment by chrisbrahms** [comment]
Sorry, totally missed this! Yes that's fine, I actually don't know why this is missing in the first place.
