### ISSUE TITLE
Question: Derivative with respect to real space coordinate

### ISSUE THREAD

**Issue by maxfreu** [chrisbrahms/Hankel.jl#38]
Hi! I used the QDHT to calculate the convolution of two radially symmetric functions via multiplication in Fourier space and then transforming back. What I am now interested in is the derivative of the convolution result with respect to the radial variable. Math-wise it should be something like this I think:

$$ \frac{d}{dr}f(r) = \frac{d}{dr}H_0^{-1}(F(k)) = \frac{d}{dr} \int_0^\infty F(k) J_0(kr)k\ dk = - \int_0^\infty F(k) J_1(kr)k^2\ dk = -H_1^{-1}(kF(k))$$

Question: Is there a nice way to obtain the result using QDHT? So far I think no, as $H_0$ and $H_1$ use different discretizations of the real and reciproke space, but I'd be happy if there's a workaround.

**Comment by sethaxen** [comment]
> Question: Is there a nice way to obtain the result using QDHT?

I can't think of a way to get this result from QDHT. My best idea would be to fit some interpolation like a spline to the values of `f` returned from the inverse transform and then use the derivative of that function. @chrisbrahms can you think of a better way?

**Comment by chrisbrahms** [comment]
Off the top of my head, I also don't think this works directly. *Maybe* you can get somewhere by expanding in a Fourier-Bessel series and using the Hankel transform to turn it into a matrix or vector multiplication, similar to what you can for integrals (see the derivation in the [docs](https://chrisbrahms.github.io/Hankel.jl/dev/derivations/#L2-norm-integrations)). But that's just speculation, I haven't tried.

**Comment by maxfreu** [comment]
> My best idea would be to fit some interpolation like a spline to the values of f returned from the inverse transform and then use the derivative of that function.

That's exactly what I ended up with and it should suffice for now. Thanks for your help!
